language: go

go:
  - 1.11.x

install: go get -v ./...

before_script: chmod +x $TRAVIS_BUILD_DIR/build.sh

script: $TRAVIS_BUILD_DIR/build.sh

deploy:
  provider: releases
  api_key: $GITHUB_RELEASE_TOKEN
  file:
    - $TRAVIS_BUILD_DIR/thanos-inspect
    - $TRAVIS_BUILD_DIR/thanos-inspect.exe
  overwrite: true
  skip_cleanup: true
  on:
    tags: true
